export const defaultPlans = [
  {
    slug: "starter-30",
    name: "30 дней",
    description: "Быстрый старт и полный доступ ко всем локациям RootVPN",
    durationDays: 30,
    amount: 49000,
    currency: "RUB",
    isPopular: false,
    features: [
      "Безлимитный трафик",
      "До 3 устройств",
      "Высокая скорость",
      "Поддержка 24/7",
    ],
  },
  {
    slug: "pro-90",
    name: "90 дней",
    description: "Оптимальный тариф для стабильного использования каждый день",
    durationDays: 90,
    amount: 129000,
    currency: "RUB",
    isPopular: true,
    features: [
      "Безлимитный трафик",
      "До 5 устройств",
      "Приоритетные серверы",
      "Поддержка 24/7",
    ],
  },
  {
    slug: "business-180",
    name: "180 дней",
    description: "Продвинутый пакет для работы и мультимедиа без ограничений",
    durationDays: 180,
    amount: 229000,
    currency: "RUB",
    isPopular: false,
    features: [
      "Безлимитный трафик",
      "До 7 устройств",
      "Премиальные маршруты",
      "Поддержка 24/7",
    ],
  },
  {
    slug: "ultra-365",
    name: "365 дней",
    description: "Максимальная выгода и защита на целый год",
    durationDays: 365,
    amount: 399000,
    currency: "RUB",
    isPopular: false,
    features: [
      "Безлимитный трафик",
      "До 10 устройств",
      "Максимальный приоритет",
      "VIP поддержка 24/7",
    ],
  },
] as const;
